// <auto-generated />
namespace HMS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class AccomodationTypeValidationRemove : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AccomodationTypeValidationRemove));
        
        string IMigrationMetadata.Id
        {
            get { return "202109181132173_AccomodationTypeValidationRemove"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
