// <auto-generated />
namespace HMS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class AccomodationTypeValidation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AccomodationTypeValidation));
        
        string IMigrationMetadata.Id
        {
            get { return "202109181115246_AccomodationTypeValidation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
